In [2]:
import cv2 
import matplotlib.pyplot as plt
import numpy as np

In [24]:
def Feature1(image_path):
    """This function calculates the number of white pixels present in the image """
    image = cv2.imread(image_path)
    if image is None:
        raise FileNotFoundError(f"Image not found at {image_path}")
    histogram = cv2.calcHist([image], [0], None, [256], [0, 256])
    plt.plot(histogram)
    threshold =200
    white_px = int(np.sum(histogram[threshold + 1:]))
    return f"{white_px/image.size:.4f}"
    
    

In [44]:
def Feature2(image_mat):
    frobenius_norm = np.linalg.norm(image_mat, 'fro')
    
    if frobenius_norm == 0:
        raise ValueError("The Frobenius norm is zero, cannot normalize.")
    
    # Normalize the image array by the Frobenius norm
    normalized_image = image_mat / frobenius_norm
    
    return normalized_image
    

In [35]:
def image_to_2d_array(image_path):
   
    # Read the image in grayscale
    image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    
    if image is None:
        raise FileNotFoundError(f"Image not found at {image_path}")
    mat = image
    return mat


In [46]:
image_mat = image_to_2d_array(r"D:\paper\waterLevel\data_1\299.jpg")
print(type(image_mat))
print(Feature2(image_mat))


<class 'numpy.ndarray'>
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
